# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wj01wmyZJUpO91-MIC_z4mp_k5t6p3wL
"""

import streamlit as st
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from ultralytics import YOLO
from PIL import Image

st.set_page_config(layout="wide", page_title="EcoTraffic AI")

st.title("🌍 EcoTraffic AI: Pemantau Emisi Kendaraan Spasial")
st.write("Unggah gambar CCTV jalan raya untuk melihat estimasi emisi karbon secara real-time.")

@st.cache_resource
def load_model():
    return YOLO('best.pt')

model = load_model()

uploaded_file = st.file_uploader("Unggah Gambar CCTV (JPG/PNG)", type=['jpg', 'png', 'jpeg'])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    img_array = np.array(image)

    results = model(img_array)
    result = results[0]

    annotated_img = result.plot()
    orig_img = result.orig_img

    if result.obb is not None:
        detected_classes = [model.names[int(cls_id)] for cls_id in result.obb.cls]
        centers_x = [box[0].item() for box in result.obb.xywhr]
        centers_y = [box[1].item() for box in result.obb.xywhr]
    else:
        detected_classes, centers_x, centers_y = [], [], []

    EMISSION_FACTORS = {'bike': 115, 'car': 192, 'taxi': 192, 'bus': 822, 'truck': 900, 'other_vehicle': 200}
    road_length_km = 0.1
    total_co2 = 0
    emission_details = []

    for vehicle in detected_classes:
        factor = EMISSION_FACTORS.get(vehicle, 150)
        co2_emitted = factor * road_length_km
        total_co2 += co2_emitted
        emission_details.append({'Kendaraan': vehicle, 'Emisi (g CO2)': co2_emitted})

    df_emissions = pd.DataFrame(emission_details)
    if not df_emissions.empty:
        df_grouped = df_emissions.groupby('Kendaraan').sum().reset_index()
    else:
        df_grouped = pd.DataFrame(columns=['Kendaraan', 'Emisi (g CO2)'])

    text_str = f"Total Emisi: {total_co2:.2f} g CO2"
    font = cv2.FONT_HERSHEY_SIMPLEX
    cv2.putText(annotated_img, text_str, (50, 100), font, 2, (0, 0, 255), 5, cv2.LINE_AA)

    fig, axes = plt.subplots(2, 2, figsize=(20, 16))

    axes[0, 0].imshow(annotated_img)
    axes[0, 0].set_title("Deteksi OBB & Kalkulasi Karbon", fontsize=16)
    axes[0, 0].axis('off')

    axes[0, 1].axis('off')
    if not df_grouped.empty:
        table = axes[0, 1].table(cellText=df_grouped.values.tolist(), colLabels=df_grouped.columns.tolist(), loc='center', cellLoc='center')
        table.auto_set_font_size(False)
        table.set_fontsize(14)
        table.scale(1, 2)
    axes[0, 1].set_title("Tabel Rincian Emisi CO2", fontsize=16)

    if not df_grouped.empty:
        sns.barplot(data=df_grouped, x='Kendaraan', y='Emisi (g CO2)', ax=axes[1, 0], palette='magma')
    axes[1, 0].set_title("Distribusi Emisi", fontsize=16)

    axes[1, 1].imshow(orig_img)
    if centers_x and centers_y:
        sns.kdeplot(x=centers_x, y=centers_y, cmap="Reds", fill=True, bw_adjust=0.5, alpha=0.5, ax=axes[1, 1])
        axes[1, 1].set_xlim(0, result.orig_shape[1])
        axes[1, 1].set_ylim(result.orig_shape[0], 0)
    axes[1, 1].set_title("Heatmap Kepadatan Spasial", fontsize=16)
    axes[1, 1].axis('off')

    st.pyplot(fig)